services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: devlog-backend
    ports:
      - "5000:5000"
    env_file:
      - .env        # backend gets everything
    networks:
      - devlog-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      args:
        - VITE_API_BASE=${VITE_API_BASE}   # pass only this to build
    container_name: devlog-frontend
    ports:
      - "80:80"
    networks:
      - devlog-network

networks:
  devlog-network:
    driver: bridge
