name: Deploy on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure AWS credentials for ECR
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 400 ec2_key.pem

          ssh -i 'ec2_key.pem' ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Login to ECR
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
              docker login --username AWS --password-stdin 948098566408.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

            # Stop running containers
            docker stop frontend || true
            docker stop backend || true

            # Remove containers
            docker rm frontend || true
            docker rm backend || true

            # Delete all old images
            docker rmi -f $(docker images -aq) || true

            # Pull latest images from ECR
            docker pull 948098566408.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/devlog-backend:latest
            docker pull 948098566408.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/devlog-frontend-ec2:latest

            # Run containers with secrets injected
            docker run -d --name frontend -p 80:80 \
              -e VITE_API_BASE=${{ secrets.VITE_API_BASE }} \
              948098566408.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/devlog-frontend-ec2:latest

            docker run -d --name backend -p 5000:5000 \
              -e MYSQL_USER=${{ secrets.MYSQL_USER }} \
              -e MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
              -e MYSQL_HOST=${{ secrets.MYSQL_HOST }} \
              -e MYSQL_PORT=${{ secrets.MYSQL_PORT }} \
              -e MYSQL_DB=${{ secrets.MYSQL_DB }} \
              -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
              -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
              -e GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
              948098566408.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/backend:latest
          EOF
